name: Link Jira Ticket

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  link_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira ticket ID
        id: extract_id
        run: echo "::set-output name=JIRA_ID::$(echo ${GITHUB_HEAD_REF} | grep -o '[A-Z0-9]\+-[0-9]\+')"
        shell: bash

      - name: Link PR to Jira ticket
        run: |
          PR_LINK="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${{ github.event.pull_request.number }}"
          COMMENT="Pull request opened: [${PR_LINK}](${PR_LINK})"
          curl -X POST -u email@example.com:${{ secrets.JIRA_API_TOKEN }} \
            -H "Content-Type: application/json" \
            -d '{"body": "'"$COMMENT"'"}' \
            "https://your-jira-instance.atlassian.net/rest/api/2/issue/${{ steps.extract_id.outputs.JIRA_ID }}/comment"
        shell: bash
